
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml  
cover: !include covers.yaml

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_iphonexr
      - service: mobile_app_irinka
      
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24      
